name: flutter_google_i18n
description: Flutter I18n managed in Google spreadsheet. This package simplifies the translations of the app by using Google spreadsheet, thanks to which a non-tech person can update texts in the app.
version: 0.0.2
homepage: https://github.com/macav/flutter-google-i18n

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async_resource: ^0.1.4
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
